# Generated by Django 5.0.2 on 2024-02-29 11:34

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('finish_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('task_text', models.TextField()),
                ('fkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menumodel')),
            ],
        ),
    ]
