# Generated by Django 5.0.2 on 2024-02-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menumodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
