# Generated by Django 5.0.2 on 2024-02-29 11:34

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasksapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('finish_date', models.TimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('reference_to_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasksapp.taskname')),
            ],
        ),
    ]
