# Generated by Django 5.0.2 on 2024-02-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subtask', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
